### ISSUE TITLE
La matrice utilisé n'est pas obligatoire une matrice carré !

### ISSUE THREAD

**Issue by Kamal-OS** [Zeek-Zone/MIP-LST-MST#1]
La matrice utilisé n'est pas obligatoire une matrice carré !

**Comment by DgrinderHZ** [comment]
Oui, j'ai fait le minimum possible! j'ai pas généralisé!

**Comment by DgrinderHZ** [comment]
Mais je vais modifier après (sur les papiers ils n'ont pas spécifier comment travailler 😝

**Comment by Zeek-Zone** [comment]
La réponse est acceptable tant qu’il est appliquée sur des matrices!
